module RTP
  module FFmpeg
    class AVFormatContext < FFI::Struct
      layout  :av_class,      :pointer,
              :iformat,       :pointer,
              :oformat,       :pointer,
              :priv_data,     :pointer,
              :pb,            :pointer,
              :nb_streams,    :uint,
              :streams,       [:pointer, MAX_STREAMS],
              :filename,      [:char, 1024],
              :timestamp,     :long_long,
              :title,         [:char, 512],
              :author,        [:char, 512],
              :copyright,     [:char, 512],
              :comment,       [:char, 512],
              :album,         [:char, 512],
              :year,          :int,
              :track,         :int,
              :genre,         [:char, 32],
              :ctx_flags,     :int,
              :packet_buffer, :pointer,
              :start_time,    :long_long,
              :duration,      :long_long,
              :file_size,     :long_long,
              :bitrate,       :int,
              :cur_st,        :pointer,
              :cur_ptr_deprecated,  :pointer,
              :cur_len_deprecated,  :int,
              :cur_pkt_deprecated,  AVPacket,
              :data_offset,   :long_long,
              :index_build,   :int,
              :mux_rate,      :int,
              :packet_size,   :uint,
              :max_delay,     :int,
              :loop_output,   :int,
              :flags,         :int,
              :loop_input,    :int,
              :probesize,     :uint,
              :max_analyze_diration,  :int,
              :key,           :pointer,
              :keylen,        :int,
              :nb_programs,   :uint,
              :programs,      :pointer,
              :video_codec_id,  :uint,      # enum CodecID
              :audio_codec_id,  :uint,      # enum CodecID
              :subtitle_codec_id, :uint,    # enum CodecID
              :max_index_size,  :uint,
              :max_picture_buffer,  :uint,
              :nb_chapters,   :uint,
              :chapters,      :pointer,
              :debug,         :int,
              :raw_packet_buffer, :pointer,
              :raw_packet_buffer_end, :pointer,
              :packet_buffet_end, :pointer,
              :metadata,      :pointer,
              :raw_packet_buffer_remaining_size, :int,
              :start_time_realtime, :long_long
    end
  end
end